language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- openjdk7
cache:
  directories:
  - $HOME/.m2/repository
install:
- cmake --version
- git submodule init
- git submodule update
script:
- mvn -Pcore-test clean install && cmake . && ctest .
